force-app/main/default/main/default/objects/Benefit_Individual__c/Benefit_Individual__c.object-meta.xml
<CustomObject>
    <label>Benefit Individual</label>
    <nameField>
        <displayFormat>BI{000}</displayFormat>
        <label>Individual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/Primary_Coverage_Holder__c.field-meta.xml
<CustomField>
    <fullName>Primary_Coverage_Holder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Coverage Holder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Benefit_Individual__c.Relation__c</field>
            <operation>equals</operation>
            <value>Self</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Benefit_Individual__c</referenceTo>
    <relationshipLabel>Benefit Individuals</relationshipLabel>
    <relationshipName>Benefit_Individuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/Coverage_Period__c.object-meta.xml
<CustomObject>
    <label>Coverage Period</label>
    <nameField>
        <label>Coverage Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Coverage_Period__c/fields/Coverage_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_End_Date__c</fullName>
    <inlineHelpText>Date until which this coverage is applicable</inlineHelpText>
    <label>Coverage End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/fields/Coverage_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Start_Date__c</fullName>
    <inlineHelpText>Date from which this coverage is applicable</inlineHelpText>
    <label>Coverage Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Type__c/Coverage_Type__c.object-meta.xml
<CustomObject>
    <label>Coverage Type</label>
    <nameField>
        <label>Coverage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Plan__c/fields/Coverage_Level__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Level__c</fullName>
    <label>Coverage Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employee + Spouse</fullName>
            </value>
            <value>
                <fullName>Employee + Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Coverage_Period__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Period__c</fullName>
    <inlineHelpText>Coverage period for which this plan is valid</inlineHelpText>
    <label>Coverage Period</label>
    <referenceTo>Coverage_Period__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan Type</label>
    <referenceTo>Coverage_Type__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/main/default/objects/Selected_Offer__c/Selected_Offer__c.object-meta.xml
<CustomObject>
    <label>Selected Offer</label>
    <nameField>
        <displayFormat>SO-{000}</displayFormat>
        <label>Selected Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Selected_Offer__c/fields/Covered_Individual__c.field-meta.xml
<CustomField>
    <fullName>Covered_Individual__c</fullName>
    <label>Covered Individual</label>
    <referenceTo>Benefit_Individual__c</referenceTo>
    <relationshipLabel>Selected Offers</relationshipLabel>
    <relationshipName>Selected_Offers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/main/default/objects/Selected_Offer__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Selected Offers</relationshipLabel>
    <relationshipName>Selected_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/main/default/objects/Selected_Offer__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <formula>Plan__r.Plan_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/main/default/classes/SelectedOfferCreateAction.cls
public with sharing class SelectedOfferCreateAction {
    
    @InvocableMethod(label='Create SelectedOffer' description='Creates SelectedOffer from provided inputs')
    public static void createSelectedOffer(List<String> input) {
        
        String selectedCoverageType = SelectedOfferCreateUtil.getSelectedCoverageTypeFromInput(input);
        Boolean waivedIndicator = SelectedOfferCreateUtil.getWaivedIndicatorFromInput(input);
       

        if(!waivedIndicator) {
            Plan__c selectedPlan = SelectedOfferCreateUtil.getPlanFromInput(input);
        	List<Benefit_Individual__c> coveredIndividuals = SelectedOfferCreateUtil.getCoveredIndividualsFromInput(input);
        	List<Boolean> selectedRelations = SelectedOfferCreateUtil.getSelectedRelations(coveredIndividuals);
        	
            validateIfSelfIsSelected(selectedRelations);
        	validateIfCorrectPlanIsSelected(selectedRelations, selectedPlan);
            
            saveSelectedOffers(coveredIndividuals, selectedPlan);
    	}
        
        else {
            removeSelectedCoveragesOfGivenType(selectedCoverageType);
        }
        
    }
    
    // Every plan must have the Salesforce Platform User as a covered individual
    private static void validateIfSelfIsSelected(List<Boolean> selectedRelations) {
        Boolean isSelfSelected = selectedRelations.get(0);
        Boolean isSpouseSelected = selectedRelations.get(1);
        Boolean isChildSelected = selectedRelations.get(2);
        
        if(!isSelfSelected) {
            throw new CalloutException('E001:You must select yourself as a covered individual');
        }
    }
    
    private static void validateIfCorrectPlanIsSelected(List<Boolean> selectedRelations, Plan__c selectedPlan) {
        
        Boolean isSelfSelected = selectedRelations.get(0);
        Boolean isSpouseSelected = selectedRelations.get(1);
        Boolean isChildSelected = selectedRelations.get(2);
        
        if(isChildSelected && selectedPlan.Coverage_Level__c != 'Employee + Family') {
            throw new CalloutException('E002:You must select a plan with coverage level as Employee + Family to cover the Child.');
        }
        
        else if(isSpouseSelected && selectedPlan.Coverage_Level__c == 'Employee') {
            throw new CalloutException('E003:You must select a plan with coverage level as Employee + Spouse to cover the Spouse.');
        }
    }
    
    private static void removeSelectedCoveragesOfGivenType(String selectedCoverageType) {
        List<Selected_Offer__c> existingSelectedOffers = [Select Id, Plan__c, Plan__r.Coverage_Period__c from Selected_Offer__c so 
                                                          where so.Plan_Type__c = :selectedCoverageType];
        
        List<Coverage_Period__c> currentlyOpenCoveragePeriod = [Select Id, Coverage_Start_Date__c, Coverage_End_Date__c from Coverage_Period__c cp where cp.Coverage_Start_Date__c <= TODAY and cp.Coverage_End_Date__c >= TODAY];
        Id selectedCoveragePeriod = currentlyOpenCoveragePeriod.get(0).Id;
        
        List<Selected_Offer__c> offersToDelete = new List<Selected_Offer__c>();
        
        for(Selected_Offer__c existingSelectedOffer: existingSelectedOffers) {
            if(existingSelectedOffer.Plan__r.Coverage_Period__c == selectedCoveragePeriod) {
                offersToDelete.add(existingSelectedOffer);
            }
        }
        
        delete offersToDelete;
    }

    private static void saveSelectedOffers(List<Benefit_Individual__c> coveredIndividuals, Plan__c selectedPlan) {
        List<Selected_Offer__c> selectedOffers = new List<Selected_Offer__c>();
        
        List<Benefit_Individual__c> connectedIndividuals = [Select Id from Benefit_Individual__c where Primary_Coverage_Holder__c in :coveredIndividuals];
        List<Benefit_Individual__c> allIndividuals = new List<Benefit_Individual__c>();
        allIndividuals.addAll(connectedIndividuals);
        allIndividuals.addAll(coveredIndividuals);
        
        String selectedPlanType = selectedPlan.Plan_Type__r.Name;
        
        List<Selected_Offer__c> existingSelectedOffers = [Select Id, Plan__c, Plan__r.Coverage_Period__c from Selected_Offer__c so 
                                                          where so.Covered_Individual__c in :allIndividuals and so.Plan_Type__c = :selectedPlanType];
        
        List<Selected_Offer__c> offersToDelete = new List<Selected_Offer__c>();
        
        Id selectedCoveragePeriod = selectedPlan.Coverage_Period__c;
        
        for(Selected_Offer__c existingSelectedOffer: existingSelectedOffers) {
            if(existingSelectedOffer.Plan__r.Coverage_Period__c == selectedCoveragePeriod) {
                offersToDelete.add(existingSelectedOffer);
            }
        }
        
        delete offersToDelete;
        
        for(Benefit_Individual__c coveredIndividual: coveredIndividuals) {
            Selected_Offer__c selectedOffer = new Selected_Offer__c(Plan__c = selectedPlan.Id, Covered_Individual__c = coveredIndividual.Id);
            selectedOffers.add(selectedOffer);
        }
        insert selectedOffers;
        
    }
}