force-app/main/default/main/default/objects/Benefit_Individual__c/Benefit_Individual__c.object-meta.xml
<CustomObject>
    <label>Benefit Individual</label>
    <nameField>
        <displayFormat>BI{000}</displayFormat>
        <label>Individual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/National_Identifier__c.field-meta.xml
<CustomField>
    <fullName>National_Identifier__c</fullName>
    <label>National Identifier</label>
    <length>9</length>
    <maskChar>X</maskChar>
    <maskType>ssn</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/Primary_Coverage_Holder__c.field-meta.xml
<CustomField>
    <fullName>Primary_Coverage_Holder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Coverage Holder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Benefit_Individual__c.Relation__c</field>
            <operation>equals</operation>
            <value>Self</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Benefit_Individual__c</referenceTo>
    <relationshipLabel>Benefit Individuals</relationshipLabel>
    <relationshipName>Benefit_Individuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/Coverage_Period__c.object-meta.xml
<CustomObject>
    <label>Coverage Period</label>
    <nameField>
        <label>Coverage Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Coverage_Period__c/fields/Coverage_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_End_Date__c</fullName>
    <inlineHelpText>Date until which this coverage is applicable</inlineHelpText>
    <label>Coverage End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/fields/Coverage_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Start_Date__c</fullName>
    <inlineHelpText>Date from which this coverage is applicable</inlineHelpText>
    <label>Coverage Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/fields/Open_Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_End_Date__c</fullName>
    <inlineHelpText>Date until which users can enroll in this coverage</inlineHelpText>
    <label>Open Enrollment End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/fields/Open_Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_Start_Date__c</fullName>
    <inlineHelpText>Date from which users can enroll in this coverage</inlineHelpText>
    <label>Open Enrollment Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Type__c/Coverage_Type__c.object-meta.xml
<CustomObject>
    <label>Coverage Type</label>
    <nameField>
        <label>Coverage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Plan__c/fields/Coverage_Level__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Level__c</fullName>
    <label>Coverage Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employee + Spouse</fullName>
            </value>
            <value>
                <fullName>Employee + Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Coverage_Period__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Period__c</fullName>
    <inlineHelpText>Coverage period for which this plan is valid</inlineHelpText>
    <label>Coverage Period</label>
    <referenceTo>Coverage_Period__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Monthly_Employee_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Employee_Cost__c</fullName>
    <inlineHelpText>Monthly cost to the employee</inlineHelpText>
    <label>Monthly Employee Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan Type</label>
    <referenceTo>Coverage_Type__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/main/default/objects/Selected_Offer__c/Selected_Offer__c.object-meta.xml
<CustomObject>
    <label>Selected Offer</label>
    <nameField>
        <displayFormat>SO-{000}</displayFormat>
        <label>Selected Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Selected_Offer__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Selected Offers</relationshipLabel>
    <relationshipName>Selected_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/main/default/objects/Selected_Offer__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <formula>Plan__r.Plan_Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/main/default/classes/SelectedOfferCreateUtilTest.cls
@IsTest 
public class SelectedOfferCreateUtilTest {

    @testSetup
    public static void setupData() {
        Coverage_Period__c covPeriod = new Coverage_Period__c(Name='Cov Period 2024', Coverage_End_Date__c = Date.newInstance(2024, 12, 31), 
                                                             Coverage_Start_Date__c = Date.newInstance(2024, 1, 1), Open_Enrollment_Start_Date__c = Date.newInstance(2023, 11, 1),
                                                             Open_Enrollment_End_Date__c = Date.newInstance(2023, 12, 31));
        insert covPeriod;
        
        Coverage_Type__c covType = new Coverage_Type__c(Name = 'Dental');
        insert covType;
        
        Plan__c plan = new Plan__c(Name='Aetna Dental', Coverage_Period__c = covPeriod.Id, Monthly_Employee_Cost__c = 100, Coverage_Level__c = 'Employee + Family', Plan_Type__c = covType.Id);
        insert plan;
        
        List<Benefit_Individual__c> coveredIndividuals = new List<Benefit_Individual__c>();
        Benefit_Individual__c self = new Benefit_Individual__c(First_Name__c = 'John', Last_name__c = 'Doe', Date_of_Birth__c = Date.newInstance(1985, 07, 05), 
                                                              National_Identifier__c = '000000000', Relation__c = 'Self');
        
        insert self;
        
        Benefit_Individual__c spouse = new Benefit_Individual__c(First_Name__c = 'Alexa', Last_name__c = 'Doe', Date_of_Birth__c = Date.newInstance(1985, 07, 05), 
                                                              National_Identifier__c = '000000000', Relation__c = 'Spouse', Primary_Coverage_Holder__c = self.Id);
        
        Benefit_Individual__c child = new Benefit_Individual__c(First_Name__c = 'John1', Last_name__c = 'Doe', Date_of_Birth__c = Date.newInstance(2023, 07, 05), 
                                                              National_Identifier__c = '000000000', Relation__c = 'Child', Primary_Coverage_Holder__c = self.Id);
        coveredIndividuals.add(spouse);
        coveredIndividuals.add(child);
        insert coveredIndividuals;
    }
    
    @IsTest
    public static void testCreateSelectedOffer() {
        Plan__c selectedPlan = [Select Id, Coverage_Level__c, Coverage_Period__c, Plan_Type__r.Name from Plan__c where Name = 'Aetna Dental'];
        List<Benefit_Individual__c> coveredIndividuals = [Select Id, Relation__c from Benefit_Individual__c where First_Name__c in ('John', 'Alexa', 'John1')];
        
        List<String> inputs = new List<String>();
        String inputStr = selectedPlan.Id + '|';
        
        for(Benefit_Individual__c individual: coveredIndividuals) {
            inputStr = inputStr + ';' + individual.Id;
        }
        
        inputStr = inputStr + '|Dental|False';
        inputs.add(inputStr);
        
        SelectedOfferCreateAction.createSelectedOffer(inputs);
        
        List<Selected_Offer__c> offersFromDb = [Select Id from Selected_Offer__c];
        
        Assert.isTrue(offersFromDb.size() == 3);
        
    }
    
    @IsTest
    public static void testGetPlanFromInput() {
        Plan__c selectedPlan = [Select Id, Coverage_Level__c, Coverage_Period__c, Plan_Type__r.Name from Plan__c where Name = 'Aetna Dental'];
        String inputStr = selectedPlan.Id;
        List<String> inputs = new List<String>();
        inputs.add(inputStr);
        
        Plan__c planFromFunc = SelectedOfferCreateUtil.getPlanFromInput(inputs);
        
        System.assertEquals(planFromFunc.Id, selectedPlan.Id);
    }
    
    @IsTest
    public static void testGetSelectedCoverageTypeFromInput() {
        String inputStr = '||Dental';
        List<String> inputs = new List<String>();
        inputs.add(inputStr);
        
        System.assertEquals(SelectedOfferCreateUtil.getSelectedCoverageTypeFromInput(inputs), 'Dental');
    }
    
    @IsTest
    public static void testGetWaivedIndicatorFromInput() {
        String inputStr = '||Dental|True';
        List<String> inputs = new List<String>();
        inputs.add(inputStr);
        
        System.assertEquals(SelectedOfferCreateUtil.getWaivedIndicatorFromInput(inputs), True);
    }
    
    @IsTest
    public static void testGetCoveredIndividualsFromInput() {
        List<Benefit_Individual__c> coveredIndividuals = [Select Id, Relation__c from Benefit_Individual__c where First_Name__c in ('John', 'Alexa', 'John1')];
        String inputStr = '|';
        for(Benefit_Individual__c individual: coveredIndividuals) {
            inputStr = inputStr + ';' + individual.Id;
        }
        inputStr = inputStr + '|Dental|True|';
        
        List<String> inputs = new List<String>();
        inputs.add(inputStr);
        
        List<Benefit_Individual__c> coveredIndividualsFromFunction = SelectedOfferCreateUtil.getCoveredIndividualsFromInput(inputs);
        System.assertEquals(coveredIndividuals, coveredIndividualsFromFunction);
    }
    
    @IsTest
    public static void testGetSelectedRelations() {
        List<Benefit_Individual__c> coveredIndividuals = [Select Id, Relation__c from Benefit_Individual__c where First_Name__c in ('John', 'Alexa', 'John1')];
        
        List<Boolean> selectedRelations = SelectedOfferCreateUtil.getSelectedRelations(coveredIndividuals);
 
        Assert.isTrue(selectedRelations.get(0) && selectedRelations.get(1) && selectedRelations.get(2));
        
    }
}