force-app/main/default/main/default/objects/Benefit_Individual__c/Benefit_Individual__c.object-meta.xml
<CustomObject>
    <label>Benefit Individual</label>
    <nameField>
        <displayFormat>BI{000}</displayFormat>
        <label>Individual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Benefit_Individual__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/main/default/objects/Coverage_Period__c/Coverage_Period__c.object-meta.xml
<CustomObject>
    <label>Coverage Period</label>
    <nameField>
        <label>Coverage Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Coverage_Type__c/Coverage_Type__c.object-meta.xml
<CustomObject>
    <label>Coverage Type</label>
    <nameField>
        <label>Coverage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Plan__c/fields/Coverage_Level__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Level__c</fullName>
    <label>Coverage Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employee + Spouse</fullName>
            </value>
            <value>
                <fullName>Employee + Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Coverage_Period__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Period__c</fullName>
    <inlineHelpText>Coverage period for which this plan is valid</inlineHelpText>
    <label>Coverage Period</label>
    <referenceTo>Coverage_Period__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/main/default/objects/Plan__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plan Type</label>
    <referenceTo>Coverage_Type__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/main/default/classes/SelectedOfferCreateUtil.cls
public class SelectedOfferCreateUtil {
    
    public static Plan__c getPlanFromInput(List<String> input) {
        String inputStr = input.get(0);
        List<String> Ids = inputStr.split('\\|');
        String planId = Ids.get(0);
        
        Plan__c selectedPlan = [Select Id, Coverage_Level__c, Coverage_Period__c, Plan_Type__r.Name from Plan__c where Id = :planId];
        return selectedPlan;
    }
    
    public static String getSelectedCoverageTypeFromInput(List<String> input) {
        String inputStr = input.get(0);
        List<String> Ids = inputStr.split('\\|');
        return Ids.get(2);
    }
    
    public static Boolean getWaivedIndicatorFromInput(List<String> input) {
        String inputStr = input.get(0);
        List<String> Ids = inputStr.split('\\|');
        return Boolean.valueOf(Ids.get(3));
    }
    
    public static List<Benefit_Individual__c> getCoveredIndividualsFromInput(List<String> input) {
        String inputStr = input.get(0);
        List<String> Ids = inputStr.split('\\|');
        String individualIdStr = Ids.get(1);
        List<String> individualIds = individualIdStr.split(';');
        
        List<String> coveredIndividualIds = new List<String>();
        
        for(Integer idIndex = 0; idIndex < individualIds.size(); idIndex++) {
            coveredIndividualIds.add(individualIds.get(idIndex));
        }
        
        List<Benefit_Individual__c> coveredIndividuals = [Select Id, Relation__c from Benefit_Individual__c where Id in :coveredIndividualIds];
        
        return coveredIndividuals;
        
    }
    
    public static List<Boolean> getSelectedRelations(List<Benefit_Individual__c> coveredIndividuals) {
        List<Boolean> selectedRelations = new List<Boolean>();
        Boolean isSpouseSelected = false;
        Boolean isChildSelected = false;
        Boolean isSelfSelected = false;
        
        for(Benefit_Individual__c coveredIndividual: coveredIndividuals) {
            if(coveredIndividual.Relation__c == 'Self') {
                isSelfSelected = true;
            }
            else if(coveredIndividual.Relation__c == 'Spouse') {
                isSpouseSelected = true;
            }
            else {
                isChildSelected = true;
            }
        }
        selectedRelations.add(isSelfSelected);
        selectedRelations.add(isSpouseSelected);
        selectedRelations.add(isChildSelected);
        
        return selectedRelations;
    }

}